### ISSUE TITLE
Hinges in general breaking 

### ISSUE THREAD

**Issue by Fevix** [Brianetta/Trailer-Manager#1]
Hi, I don't think this is the fault of Trailer Manager, but I don't know where else to report this. 

After using ISL's trailers, I've found that hinges very quickly lose the ability to attach/detach to existing heads. I'll move into position, and press attach, and so far I'll have about a 50% chance of it actually attaching. If it doesn't, no hinge will ever attach to an existing head ever again until I reload the world completely. 

Is this due to something I'm doing wrong somehow?

**Comment by Brianetta** [comment]
I couldn't tell you, I'm afraid. This isn't behaviour that I've encountered. It's worth checking the button's actions, to make sure it's still attempting to attach the corect hinge (replacement hinges aren't automatically associated, even if welded from a projection). Other than that, if you have steps to reproduce the issue in an un-modded world it's worth opening a bug report on [Keen's support site](https://support.keenswh.com).
